import re
import os

# Script: Log Search Utility
# Description: Allows users to search for log events based on log message or log level
# Date: August 2023

def search_level_events(file_path):
    """ This function searches for events based on user's inputted log level. 
        It prints all found log levels found onto the console.
        
    Args:
        file_path: This file contains the logs generated from my point-of-sale system
    """
    
    level_pattern = input("\nType in log level (e.g., INFO, FINE): ")
    level_pattern = level_pattern.upper()
    
    # Empty list to store found logs
    logs_level = []
   
   # Open and read the log file line by line. Uses regex to search for a match.
    with open(file_path, 'r') as log_file:
        
        for log in log_file:
            
            if level_pattern not in log:
                continue
           
            result = re.search(r'\b{}\b'.format(level_pattern), log)
            
            # If a result (the level) is found within the line, it appends it to the logs_level list
            if result:
                logs_level.append(log) 

    # Displays results
    print("\n---------------------------------------------------------------------------------")
    if not logs_level:
        print("Level not found. Available levels include: Warning, Info, Config, Fine, Finer")
    for log_level in logs_level:
        print(log_level, end = '')
    print("---------------------------------------------------------------------------------\n")
     
     
def search_message_events(file_path):
    """ This function searches for events based on user's inputted log message (events)

    Args:
        file_path: This file contains the logs generated from my point-of-sale system
    """
    
    message_pattern = input("\nEnter log message (e.g., new transaction): ")
    
    # This splits the log message into a list
    message_list_pattern = message_pattern.split()
    
    # Empty list to store found logs
    found_messages = []

    # Open and read the log file line by line. Uses regex to search for a match.
    with open(file_path, 'r') as log_file:
        for log in log_file:
            
            # If all the words in the inputted log message is found, it'll append to the found_messages list
            if all(re.search(r': .*{}.*'.format(message.lower()), log.lower()) for message in message_list_pattern):
                found_messages.append(log)


    # Displays results
    print("\n---------------------------------------------------------------------------------")
    if not found_messages:
        print("No messages found.")
    else:
        for message in found_messages:
            print(message, end = '')
    print("---------------------------------------------------------------------------------\n")


def main():
    """ This is the entry point of the program. It prompts users to select the type of query to search for logs.
        Users can either do a search based on the log level or log message.
        
        This also allows users to perform multiple searches or exit the program.
    """
    
    loop = True
    initial_query = False
    
    # The designated file path, which points to a log file generated by my point-of-sale system.
    file_path = "scripts/sample_logs.txt"
    file_path = os.path.abspath(file_path)
   
    while loop:
        try:
            answer = int(input("\nEnter Selection.\n1: Search an event based on its log level.\n2: Search an event based on its log message.\n--> "))
            
            if  0 < answer < 3:
                if answer == 1:
                    search_level_events(file_path)
                if answer == 2:
                    search_message_events(file_path)
            
                initial_query = True
                
        except ValueError:
            continue
   
        if initial_query == False:
            continue
       
        while True:
            try:
                loop_answer = int(input("Another search query?\n1: Yes.\n2: No.\n--> "))
                if 0 < loop_answer < 3:
                    if loop_answer == 1:
                        loop = True
                        break
                    else:
                        loop = False
                        break
                else:
                    print("")
                           
            except ValueError:
                print("")
           
   
main()
